### PR TITLE
Update shared.lua

### PR DESCRIPTION
**Pull request by KiriGo**
Translated to Russian

### CODE REVIEW

**Comment by VictorienXP** [comment]
No, you can't translate everything, you can only translate GM.Strings

**Comment by KiriGo** [comment]
Some narrow place to work. Yes, and I translated all that considered possible. I did not mean to rewrite everything as I have shown. You just might add that it was displayed for those with Russian language ... and I, where do I have to translate the added two missing lines. Why do not you reconsider my version and to add something, something to add, supplement ...

**Comment by VictorienXP** [comment]
Yes some stuff are ok. But I can't modify commits.

**Comment by VictorienXP** [comment]
The fixed translations and new translation has been added in af7508ffd2568e0d600502c4fc79042ea0ea5237

**Pull request closed without merging**
